#!/usr/bin/env python3
"""Build every generated palette artifact from the authoritative definitions."""

from __future__ import annotations

import argparse
import json
import plistlib
import sys
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from render_gallery import GALLERY_FINGERPRINT_KEY, render_matplotlib_gallery
from render_samples import (
    channel_collapse_svg,
    failure_modes_svg,
    redundant_encoding_svg,
    render_samples,
    sample_analysis_markdown,
)
from render_story import render_readme_story

from redshift_safe.color import contrast_ratio, hex_to_srgb
from redshift_safe.generate import ANSI_NAMES, generate_manifest

BASE_MANAGED_PATHS = (
    "palettes/redshift-safe-palettes.json",
    "palettes/redshift-safe-palettes.css",
    "src/redshift_safe/palettes.json",
    "themes/terminal/README.md",
    "docs/swatches/overview.svg",
    "docs/swatches/command-vs-simulated.png",
    "docs/matplotlib-gallery.png",
    "docs/samples/terminal-commanded.png",
    "docs/samples/terminal-simulated.png",
    "docs/samples/terminal-story.png",
    "docs/samples/data-commanded.png",
    "docs/samples/data-simulated.png",
    "docs/samples/data-story.png",
    "docs/diagrams/channel-collapse.svg",
    "docs/diagrams/failure-modes.svg",
    "docs/diagrams/redundant-encoding.svg",
    "docs/sample-analysis.md",
)


def _write(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content, encoding="utf-8")


def _css(manifest: dict) -> str:
    lines = [
        "/* Generated by tools/build_all.py. Do not edit by hand. */",
        "/* Continuous maps expose 11 representative stops; use JSON/Python for all 256. */",
        "",
    ]
    for slug, family in manifest["families"].items():
        selectors = [slug]
        selectors.extend(
            legacy
            for legacy, current in manifest.get("legacy_aliases", {}).items()
            if current == slug
        )
        lines.append(
            ",\n".join(f'[data-redshift-palette="{selector}"]' for selector in selectors) + " {"
        )
        for name, value in family["surfaces"].items():
            lines.append(f"  --rs-{name.replace('_', '-')}: {value};")
        for legacy, canonical in manifest.get("legacy_surface_role_aliases", {}).items():
            value = family["surfaces"][canonical]
            lines.append(f"  --rs-{legacy.replace('_', '-')}: {value}; /* legacy alias */")
        for name, value in family["categorical"].items():
            lines.append(f"  --rs-category-{name}: {value};")
        continuous = family["continuous_hex8"]
        stops = [continuous[round(i * 255 / 10)] for i in range(11)]
        gradient = ", ".join(f"{color} {i * 10}%" for i, color in enumerate(stops))
        lines.append(f"  --rs-sequential: linear-gradient(90deg, {gradient});")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _alacritty(family: dict) -> str:
    terminal = family["terminal"]
    normal = {name: terminal[name] for name in ANSI_NAMES[:8]}
    bright = {name.removeprefix("bright_"): terminal[name] for name in ANSI_NAMES[8:]}
    lines = [
        "# Generated by ember-redshift-safe-palettes/tools/build_all.py",
        f"# Family: {family['name']}",
        "[colors.primary]",
        f'background = "{family["surfaces"]["bg_0"]}"',
        f'foreground = "{family["surfaces"]["fg_0"]}"',
        "",
        "[colors.selection]",
        f'background = "{family["surfaces"]["bg_5"]}"',
        f'text = "{family["surfaces"]["fg_0"]}"',
        "",
        "[colors.normal]",
    ]
    lines.extend(f'{name} = "{value}"' for name, value in normal.items())
    lines.extend(("", "[colors.bright]"))
    lines.extend(f'{name} = "{value}"' for name, value in bright.items())
    return "\n".join(lines) + "\n"


def _windows_terminal(family: dict) -> str:
    terminal = family["terminal"]
    mapping = {
        "black": "black",
        "red": "red",
        "green": "green",
        "yellow": "yellow",
        "blue": "blue",
        "purple": "magenta",
        "cyan": "cyan",
        "white": "white",
        "brightBlack": "bright_black",
        "brightRed": "bright_red",
        "brightGreen": "bright_green",
        "brightYellow": "bright_yellow",
        "brightBlue": "bright_blue",
        "brightPurple": "bright_magenta",
        "brightCyan": "bright_cyan",
        "brightWhite": "bright_white",
    }
    payload = {"name": family["name"]}
    payload.update({key: terminal[value] for key, value in mapping.items()})
    payload["background"] = family["surfaces"]["bg_0"]
    payload["foreground"] = family["surfaces"]["fg_0"]
    payload["selectionBackground"] = family["surfaces"]["bg_5"]
    return json.dumps(payload, indent=2) + "\n"


def _iterm_color(value: str) -> dict:
    rgb = hex_to_srgb(value)
    return {
        "Alpha Component": 1.0,
        "Blue Component": float(rgb[2]),
        "Color Space": "sRGB",
        "Green Component": float(rgb[1]),
        "Red Component": float(rgb[0]),
    }


def _iterm(family: dict) -> bytes:
    terminal = family["terminal"]
    payload = {
        "Background Color": _iterm_color(family["surfaces"]["bg_0"]),
        "Foreground Color": _iterm_color(family["surfaces"]["fg_0"]),
        "Bold Color": _iterm_color(family["surfaces"]["fg_0"]),
        "Selection Color": _iterm_color(family["surfaces"]["bg_5"]),
        "Selected Text Color": _iterm_color(family["surfaces"]["fg_0"]),
    }
    for index, name in enumerate(ANSI_NAMES):
        payload[f"Ansi {index} Color"] = _iterm_color(terminal[name])
    return plistlib.dumps(payload, sort_keys=True)


def _svg_text(x: int, y: int, value: str, size: int = 14, fill: str = "#E9E1D4") -> str:
    escaped = value.replace("&", "&amp;").replace("<", "&lt;")
    return f'<text x="{x}" y="{y}" fill="{fill}" font-size="{size}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace">{escaped}</text>'


def _label_color(background: str) -> str:
    dark = "#14110E"
    light = "#FFF0D8"
    background_rgb = hex_to_srgb(background)
    dark_contrast = contrast_ratio(background_rgb, hex_to_srgb(dark))
    light_contrast = contrast_ratio(background_rgb, hex_to_srgb(light))
    return dark if dark_contrast >= light_contrast else light


def _family_svg(family: dict, profile: dict) -> str:
    width, height = 1180, 430
    canvas = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" rx="18" fill="#151310"/>',
        _svg_text(28, 38, family["name"], 24),
        _svg_text(28, 62, f"{profile['target']} · commanded sRGB", 13, "#B9AC98"),
    ]
    x, y = 28, 88
    surface_step = (width - 56) / len(family["surfaces"])
    for name, value in family["surfaces"].items():
        canvas.append(
            f'<rect x="{x:.2f}" y="{y}" width="{surface_step - 8:.2f}" '
            f'height="52" rx="6" fill="{value}" stroke="#665D50"/>'
        )
        label_fill = _label_color(value)
        canvas.append(
            _svg_text(
                x + 8,
                y + 21,
                name.replace("background", "bg").replace("foreground", "fg"),
                11,
                label_fill,
            )
        )
        canvas.append(_svg_text(x + 8, y + 41, value, 12, label_fill))
        x += surface_step
    canvas.append(_svg_text(28, 174, "ANSI 0–15", 13, "#B9AC98"))
    x, y = 28, 187
    for value in family["terminal"].values():
        canvas.append(f'<rect x="{x}" y="{y}" width="68" height="44" fill="{value}"/>')
        x += 68
    count = len(family["categorical"])
    canvas.append(_svg_text(28, 264, f"Categorical 1–{count}", 13, "#B9AC98"))
    x, y = 28, 278
    width_per_color = min(170, 1080 // count)
    for value in family["categorical"].values():
        canvas.append(
            f'<rect x="{x}" y="{y}" width="{width_per_color - 8}" '
            f'height="58" rx="5" fill="{value}"/>'
        )
        canvas.append(_svg_text(x + 14, y + 36, value, 13, _label_color(value)))
        x += width_per_color
    continuous = family["continuous_hex8"]
    canvas.append(_svg_text(28, 370, "Sequential (low → high)", 13, "#B9AC98"))
    x, y = 28, 384
    for index, value in enumerate(continuous):
        canvas.append(
            f'<rect x="{x + index * 4.32:.2f}" y="{y}" width="4.5" height="24" fill="{value}"/>'
        )
    canvas.append("</svg>")
    return "\n".join(canvas)


def _overview_svg(manifest: dict) -> str:
    width, header, row_height, footer = 760, 88, 260, 52
    height = header + row_height * len(manifest["families"]) + footer
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" rx="18" fill="#12100E"/>',
        _svg_text(24, 42, "The four Ember palettes", 30),
        _svg_text(
            24,
            70,
            "Every authored color, as applications request it (filter off).",
            17,
            "#BDAE98",
        ),
    ]
    background_roles = manifest["quality_targets"]["bg_roles_low_to_high"]
    foreground_roles = ["fg_0", "fg_1", "fg_2"]
    terminal_roles = (
        ("red", "R"),
        ("green", "G"),
        ("yellow", "Y"),
        ("blue", "B"),
        ("magenta", "M"),
        ("cyan", "C"),
    )
    for row, family in enumerate(manifest["families"].values()):
        y = header + row * row_height
        if row:
            parts.append(f'<line x1="24" y1="{y}" x2="736" y2="{y}" stroke="#3B342C"/>')
        parts.append(_svg_text(24, y + 30, family["name"], 24))

        indices = family["terminal_ansi_indices"]
        first_letter_by_index: dict[int, str] = {}
        terminal_labels = []
        for (_, letter), index in zip(terminal_roles, indices):
            first = first_letter_by_index.setdefault(index, letter)
            terminal_labels.append(letter if first == letter else f"{letter}={first}")
        alias_text = ", ".join(label for label in terminal_labels if "=" in label)
        capacity = (
            f"{len(family['categorical'])} categories / "
            f"{family['terminal_semantic_color_count']} accents"
        )
        if alias_text:
            capacity += f" ({alias_text})"
        escaped_capacity = capacity.replace("&", "&amp;").replace("<", "&lt;")
        parts.append(
            f'<text x="736" y="{y + 29}" text-anchor="end" fill="#BDAE98" font-size="18" '
            f'font-family="ui-monospace, SFMono-Regular, Menlo, monospace">{escaped_capacity}</text>'
        )

        parts.append(
            _svg_text(24, y + 54, "SURFACES bg_0 to bg_5 / TEXT fg_0 to fg_2", 14, "#BDAE98")
        )
        surface_roles = [*background_roles, *foreground_roles]
        surface_gap = 4
        surface_width = (712 - surface_gap * (len(surface_roles) - 1)) / len(surface_roles)
        for index, role in enumerate(surface_roles):
            value = family["surfaces"][role]
            x = 24 + index * (surface_width + surface_gap)
            parts.append(
                f'<rect x="{x:.2f}" y="{y + 62}" width="{surface_width:.2f}" '
                f'height="38" rx="5" fill="{value}"/>'
            )
            parts.append(_svg_text(round(x + 8), y + 87, role, 13, _label_color(value)))

        categorical = list(family["categorical"].values())
        parts.append(_svg_text(24, y + 122, "CATEGORIES", 14, "#BDAE98"))
        categorical_width, categorical_gap = 430, 6
        each_category = (categorical_width - categorical_gap * (len(categorical) - 1)) / len(
            categorical
        )
        for index, value in enumerate(categorical):
            x = 24 + index * (each_category + categorical_gap)
            parts.append(
                f'<rect x="{x:.2f}" y="{y + 132}" width="{each_category:.2f}" '
                f'height="42" rx="5" fill="{value}"/>'
            )

        sequential_x, sequential_width = 476, 260
        parts.append(_svg_text(sequential_x, y + 122, "SEQUENTIAL low to high", 14, "#BDAE98"))
        for index, value in enumerate(family["continuous_hex8"]):
            x = sequential_x + index * sequential_width / len(family["continuous_hex8"])
            parts.append(
                f'<rect x="{x:.2f}" y="{y + 132}" width="1.15" height="42" fill="{value}"/>'
            )

        parts.append(_svg_text(24, y + 196, "TERMINAL ANSI ACCENTS", 14, "#BDAE98"))
        terminal_gap = 6
        terminal_width = (712 - terminal_gap * (len(terminal_roles) - 1)) / len(terminal_roles)
        for index, ((role, _letter), label) in enumerate(zip(terminal_roles, terminal_labels)):
            value = family["terminal"][role]
            x = 24 + index * (terminal_width + terminal_gap)
            parts.append(
                f'<rect x="{x:.2f}" y="{y + 206}" width="{terminal_width:.2f}" '
                f'height="42" rx="5" fill="{value}"/>'
            )
            parts.append(_svg_text(round(x + 12), y + 233, label, 18, _label_color(value)))
    footer_y = header + row_height * len(manifest["families"])
    parts.append(
        _svg_text(
            24,
            footer_y + 32,
            "Deep filters destroy identities; Ember authors fewer instead of faking more.",
            16,
            "#BDAE98",
        )
    )
    parts.append("</svg>")
    return "\n".join(parts)


def build(destination: Path) -> None:
    manifest = generate_manifest()
    encoded = json.dumps(manifest, indent=2) + "\n"
    _write(destination / "palettes/redshift-safe-palettes.json", encoded)
    _write(destination / "src/redshift_safe/palettes.json", encoded)
    _write(destination / "palettes/redshift-safe-palettes.css", _css(manifest))
    terminal_readme = """# Terminal themes

Generated imports are provided for Alacritty, iTerm2, and Windows Terminal. Each
uses the family’s primary background and foreground. Alternative surfaces live in
the JSON manifest, generated CSS, and Python `surfaces()` API; substitute them when a
different canvas is needed. Terminal formats themselves expose only their native primary
background and selection roles; generated themes map those to `bg_0` and `bg_5`.

## Install

### Alacritty

Copy one TOML file into your Alacritty configuration directory, then import it
from `alacritty.toml`:

```toml
[general]
import = ["~/.config/alacritty/themes/2000k-dark.toml"]
```

Restart Alacritty or reload its configuration.

### iTerm2

Open **Settings → Profiles → Colors → Color Presets… → Import…**, choose a
`.itermcolors` file, then select the imported preset from **Color Presets…**.

### Windows Terminal

Open **Settings → Open JSON file**. Copy one generated scheme object into the
root `schemes` array, then set a profile’s `colorScheme` to the object’s exact
`name` value, such as `2000K Dark`.

## Surface roles

Terminal formats require all 16 ANSI slots. Ember repeats 6, 6, 4, or 3
commanded daytime accents across those slots. Under the target transforms they form
6, 6, 4, or 3 distinct nighttime identities. Bold should come from typography,
not a second high-chroma bank.

Reduced banks preserve recognizable ANSI roles by day. At 1200 K, magenta aliases red,
cyan aliases green, and blue aliases yellow instead of using a modulo cycle that would
assign those names to misleading hues.

`fg_0` is the body-text role. `fg_1` is intended for larger supporting text or graphics,
and `fg_2` for nonessential metadata or decoration. The latter two are not universal
body-text colors; inspect each
pairing under `metrics.shifted_text_contrast` in the JSON manifest.
"""
    _write(destination / "themes/terminal/README.md", terminal_readme)

    for slug, family in manifest["families"].items():
        _write(destination / f"themes/terminal/alacritty/{slug}.toml", _alacritty(family))
        _write(
            destination / f"themes/terminal/windows-terminal/{slug}.json", _windows_terminal(family)
        )
        _write(destination / f"themes/terminal/iterm2/{slug}.itermcolors", _iterm(family))
        profile = manifest["profiles"][family["profile"]]
        _write(destination / f"docs/swatches/{slug}.svg", _family_svg(family, profile))

    for legacy, current in manifest.get("legacy_aliases", {}).items():
        family = manifest["families"][current]
        profile = manifest["profiles"][family["profile"]]
        _write(destination / f"themes/terminal/alacritty/{legacy}.toml", _alacritty(family))
        _write(
            destination / f"themes/terminal/windows-terminal/{legacy}.json",
            _windows_terminal(family),
        )
        _write(destination / f"themes/terminal/iterm2/{legacy}.itermcolors", _iterm(family))
        _write(destination / f"docs/swatches/{legacy}.svg", _family_svg(family, profile))

    _write(destination / "docs/swatches/overview.svg", _overview_svg(manifest))
    render_readme_story(manifest, destination / "docs")
    render_matplotlib_gallery(manifest, destination / "docs/matplotlib-gallery.png")
    render_samples(manifest, destination / "docs/samples")
    _write(destination / "docs/diagrams/channel-collapse.svg", channel_collapse_svg())
    _write(destination / "docs/diagrams/failure-modes.svg", failure_modes_svg(manifest))
    _write(
        destination / "docs/diagrams/redundant-encoding.svg",
        redundant_encoding_svg(),
    )
    _write(
        destination / "docs/sample-analysis.md",
        sample_analysis_markdown(manifest, destination / "docs/samples"),
    )


def _artifacts_equal(expected: Path, actual: Path) -> bool:
    if not actual.exists():
        return False
    if expected.suffix == ".png":
        with Image.open(expected) as left, Image.open(actual) as right:
            if expected.name == "matplotlib-gallery.png":
                # Matplotlib text rasterization varies across supported Python/platform
                # wheels. Compare the source fingerprint and canvas, not incidental pixels.
                return left.size == right.size and left.info.get(
                    GALLERY_FINGERPRINT_KEY
                ) == right.info.get(GALLERY_FINGERPRINT_KEY)
            return np.array_equal(np.asarray(left.convert("RGB")), np.asarray(right.convert("RGB")))
    return actual.read_bytes() == expected.read_bytes()


def check() -> int:
    with tempfile.TemporaryDirectory() as directory:
        temp = Path(directory)
        build(temp)
        failures = []
        manifest = generate_manifest()
        generated_paths = [Path(path) for path in BASE_MANAGED_PATHS]
        for slug in manifest["families"]:
            generated_paths.extend(
                (
                    Path(f"docs/swatches/{slug}.svg"),
                    Path(f"themes/terminal/alacritty/{slug}.toml"),
                    Path(f"themes/terminal/iterm2/{slug}.itermcolors"),
                    Path(f"themes/terminal/windows-terminal/{slug}.json"),
                )
            )
        for legacy in manifest.get("legacy_aliases", {}):
            generated_paths.extend(
                (
                    Path(f"docs/swatches/{legacy}.svg"),
                    Path(f"themes/terminal/alacritty/{legacy}.toml"),
                    Path(f"themes/terminal/iterm2/{legacy}.itermcolors"),
                    Path(f"themes/terminal/windows-terminal/{legacy}.json"),
                )
            )
        for relative in generated_paths:
            expected = temp / relative
            actual = ROOT / relative
            if not _artifacts_equal(expected, actual):
                failures.append(str(relative))
        if failures:
            print("stale generated files:")
            print("\n".join(f"  {path}" for path in failures))
            return 1
    print("generated artifacts are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check()
    build(ROOT)
    print("built palette data, terminal themes, and swatches")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
