#!/usr/bin/env python3
"""Build every generated palette artifact from the authoritative definitions."""

from __future__ import annotations

import argparse
import json
import plistlib
import shutil
import sys
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from redshift_safe.color import contrast_ratio, hex_to_srgb, warm_transform  # noqa: E402
from redshift_safe.generate import ANSI_NAMES, generate_manifest  # noqa: E402

BASE_MANAGED_PATHS = (
    "palettes/redshift-safe-palettes.json",
    "palettes/redshift-safe-palettes.css",
    "src/redshift_safe/palettes.json",
    "themes/terminal/README.md",
    "docs/swatches/overview.svg",
    "docs/swatches/command-vs-simulated.png",
)


def _write(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content, encoding="utf-8")


def _css(manifest: dict) -> str:
    lines = [
        "/* Generated by tools/build_all.py. Do not edit by hand. */",
        "/* Continuous maps expose 11 representative stops; use JSON/Python for all 256. */",
        "",
    ]
    for slug, family in manifest["families"].items():
        lines.append(f'[data-redshift-palette="{slug}"] {{')
        for name, value in family["surfaces"].items():
            lines.append(f"  --rs-{name.replace('_', '-')}: {value};")
        for name, value in family["categorical"].items():
            lines.append(f"  --rs-category-{name}: {value};")
        continuous = family["continuous"]
        stops = [continuous[round(i * 255 / 10)] for i in range(11)]
        gradient = ", ".join(f"{color} {i * 10}%" for i, color in enumerate(stops))
        lines.append(f"  --rs-sequential: linear-gradient(90deg, {gradient});")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _alacritty(family: dict) -> str:
    terminal = family["terminal"]
    normal = {name: terminal[name] for name in ANSI_NAMES[:8]}
    bright = {name.removeprefix("bright_"): terminal[name] for name in ANSI_NAMES[8:]}
    lines = [
        "# Generated by redshift-safe-palettes/tools/build_all.py",
        f"# Family: {family['name']}",
        "[colors.primary]",
        f'background = "{family["surfaces"]["background"]}"',
        f'foreground = "{family["surfaces"]["foreground"]}"',
        "",
        "[colors.selection]",
        f'background = "{family["surfaces"]["selection"]}"',
        f'text = "{family["surfaces"]["foreground"]}"',
        "",
        "[colors.normal]",
    ]
    lines.extend(f'{name} = "{value}"' for name, value in normal.items())
    lines.extend(("", "[colors.bright]"))
    lines.extend(f'{name} = "{value}"' for name, value in bright.items())
    return "\n".join(lines) + "\n"


def _windows_terminal(family: dict) -> str:
    terminal = family["terminal"]
    mapping = {
        "black": "black",
        "red": "red",
        "green": "green",
        "yellow": "yellow",
        "blue": "blue",
        "purple": "magenta",
        "cyan": "cyan",
        "white": "white",
        "brightBlack": "bright_black",
        "brightRed": "bright_red",
        "brightGreen": "bright_green",
        "brightYellow": "bright_yellow",
        "brightBlue": "bright_blue",
        "brightPurple": "bright_magenta",
        "brightCyan": "bright_cyan",
        "brightWhite": "bright_white",
    }
    payload = {"name": family["name"]}
    payload.update({key: terminal[value] for key, value in mapping.items()})
    payload["background"] = family["surfaces"]["background"]
    payload["foreground"] = family["surfaces"]["foreground"]
    payload["selectionBackground"] = family["surfaces"]["selection"]
    return json.dumps(payload, indent=2) + "\n"


def _iterm_color(value: str) -> dict:
    rgb = hex_to_srgb(value)
    return {
        "Alpha Component": 1.0,
        "Blue Component": float(rgb[2]),
        "Color Space": "sRGB",
        "Green Component": float(rgb[1]),
        "Red Component": float(rgb[0]),
    }


def _iterm(family: dict) -> bytes:
    terminal = family["terminal"]
    payload = {
        "Background Color": _iterm_color(family["surfaces"]["background"]),
        "Foreground Color": _iterm_color(family["surfaces"]["foreground"]),
        "Bold Color": _iterm_color(family["surfaces"]["foreground"]),
        "Selection Color": _iterm_color(family["surfaces"]["selection"]),
        "Selected Text Color": _iterm_color(family["surfaces"]["foreground"]),
    }
    for index, name in enumerate(ANSI_NAMES):
        payload[f"Ansi {index} Color"] = _iterm_color(terminal[name])
    return plistlib.dumps(payload, sort_keys=True)


def _svg_text(x: int, y: int, value: str, size: int = 14, fill: str = "#E9E1D4") -> str:
    escaped = value.replace("&", "&amp;").replace("<", "&lt;")
    return f'<text x="{x}" y="{y}" fill="{fill}" font-size="{size}" font-family="ui-monospace, SFMono-Regular, Menlo, monospace">{escaped}</text>'


def _label_color(background: str) -> str:
    dark = "#14110E"
    light = "#FFF0D8"
    background_rgb = hex_to_srgb(background)
    dark_contrast = contrast_ratio(background_rgb, hex_to_srgb(dark))
    light_contrast = contrast_ratio(background_rgb, hex_to_srgb(light))
    return dark if dark_contrast >= light_contrast else light


def _family_svg(family: dict, profile: dict) -> str:
    width, height = 1180, 430
    canvas = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" rx="18" fill="#151310"/>',
        _svg_text(28, 38, family["name"], 24),
        _svg_text(28, 62, f'{profile["target"]} · commanded sRGB', 13, "#B9AC98"),
    ]
    x, y = 28, 88
    for name, value in family["surfaces"].items():
        canvas.append(f'<rect x="{x}" y="{y}" width="142" height="52" rx="6" fill="{value}" stroke="#665D50"/>')
        label_fill = _label_color(value)
        canvas.append(_svg_text(x + 8, y + 21, name.replace("background", "bg").replace("foreground", "fg"), 11, label_fill))
        canvas.append(_svg_text(x + 8, y + 41, value, 12, label_fill))
        x += 158
    canvas.append(_svg_text(28, 174, "ANSI 0–15", 13, "#B9AC98"))
    x, y = 28, 187
    for value in family["terminal"].values():
        canvas.append(f'<rect x="{x}" y="{y}" width="68" height="44" fill="{value}"/>')
        x += 68
    canvas.append(_svg_text(28, 264, "Categorical 1–8", 13, "#B9AC98"))
    x, y = 28, 278
    for value in family["categorical"].values():
        canvas.append(f'<rect x="{x}" y="{y}" width="132" height="58" rx="5" fill="{value}"/>')
        canvas.append(_svg_text(x + 21, y + 36, value, 13, _label_color(value)))
        x += 140
    continuous = family["continuous"]
    canvas.append(_svg_text(28, 370, "Sequential (low → high)", 13, "#B9AC98"))
    x, y = 28, 384
    for index, value in enumerate(continuous):
        canvas.append(f'<rect x="{x + index * 4.32:.2f}" y="{y}" width="4.5" height="24" fill="{value}"/>')
    canvas.append("</svg>")
    return "\n".join(canvas)


def _overview_svg(manifest: dict) -> str:
    width, row_height = 1200, 154
    height = row_height * 6 + 36
    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" rx="18" fill="#12100E"/>',
    ]
    profile_labels = {
        "nightshift": "~3400 K warm-white surrogate",
        "redshift": "Redshift 2000 K pinned signal-LUT",
        "safelight": "Redshift 1200 K pinned LUT",
    }
    for row, family in enumerate(manifest["families"].values()):
        y = 24 + row * row_height
        parts.append(_svg_text(24, y + 22, family["name"], 20))
        parts.append(_svg_text(24, y + 43, profile_labels[family["profile"]], 12, "#AFA18D"))
        x = 285
        for value in family["categorical"].values():
            parts.append(f'<rect x="{x}" y="{y}" width="63" height="52" rx="5" fill="{value}"/>')
            x += 68
        x, gradient_y = 285, y + 68
        for index, value in enumerate(family["continuous"]):
            parts.append(f'<rect x="{x + index * 3.37:.2f}" y="{gradient_y}" width="3.6" height="28" fill="{value}"/>')
        parts.append(f'<rect x="{285}" y="{y + 108}" width="860" height="22" rx="4" fill="{family["surfaces"]["background"]}"/>')
        parts.append(_svg_text(300, y + 124, "Aa  foreground / background", 12, family["surfaces"]["foreground"]))
    parts.append("</svg>")
    return "\n".join(parts)


def _preview_png(manifest: dict, path: Path) -> None:
    width, row_height = 1500, 176
    image = Image.new("RGB", (width, row_height * 6 + 50), "#11100E")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default(size=18)
    small = ImageFont.load_default(size=14)
    for row, family in enumerate(manifest["families"].values()):
        y = 24 + row * row_height
        profile = manifest["profiles"][family["profile"]]
        gains = profile["rgb_gains"]
        draw.text((20, y), family["name"], font=font, fill="#EEE4D5")
        draw.text((20, y + 25), "command", font=small, fill="#BCAE9A")
        draw.text((20, y + 94), "simulated", font=small, fill="#BCAE9A")
        values = list(family["categorical"].values())
        for index, value in enumerate(values):
            rgb = tuple(round(channel * 255) for channel in hex_to_srgb(value))
            shifted = tuple(round(channel * 255) for channel in warm_transform(hex_to_srgb(value), gains))
            x = 150 + index * 112
            draw.rounded_rectangle((x, y + 18, x + 100, y + 74), 5, fill=rgb)
            draw.rounded_rectangle((x, y + 88, x + 100, y + 144), 5, fill=shifted)
        sequence = family["continuous"]
        for index, value in enumerate(sequence):
            rgb = tuple(round(channel * 255) for channel in hex_to_srgb(value))
            shifted = tuple(round(channel * 255) for channel in warm_transform(hex_to_srgb(value), gains))
            x = 1075 + index
            draw.line((x, y + 18, x, y + 74), fill=rgb)
            draw.line((x, y + 88, x, y + 144), fill=shifted)
    path.parent.mkdir(parents=True, exist_ok=True)
    image.save(path, optimize=True)


def build(destination: Path) -> None:
    manifest = generate_manifest()
    encoded = json.dumps(manifest, indent=2) + "\n"
    _write(destination / "palettes/redshift-safe-palettes.json", encoded)
    _write(destination / "src/redshift_safe/palettes.json", encoded)
    _write(destination / "palettes/redshift-safe-palettes.css", _css(manifest))
    terminal_readme = """# Terminal themes\n\nGenerated imports are provided for Alacritty, iTerm2, and Windows Terminal. Each\nuses the family’s primary background and foreground. Alternative surfaces live in\n`palettes/redshift-safe-palettes.json`; substitute them when a dimmer or more\nseparated canvas is needed.\n"""
    _write(destination / "themes/terminal/README.md", terminal_readme)

    for slug, family in manifest["families"].items():
        _write(destination / f"themes/terminal/alacritty/{slug}.toml", _alacritty(family))
        _write(destination / f"themes/terminal/windows-terminal/{slug}.json", _windows_terminal(family))
        _write(destination / f"themes/terminal/iterm2/{slug}.itermcolors", _iterm(family))
        profile = manifest["profiles"][family["profile"]]
        _write(destination / f"docs/swatches/{slug}.svg", _family_svg(family, profile))

    _write(destination / "docs/swatches/overview.svg", _overview_svg(manifest))
    _preview_png(manifest, destination / "docs/swatches/command-vs-simulated.png")


def _artifacts_equal(expected: Path, actual: Path) -> bool:
    if not actual.exists():
        return False
    if expected.suffix == ".png":
        with Image.open(expected) as left, Image.open(actual) as right:
            return np.array_equal(np.asarray(left.convert("RGB")), np.asarray(right.convert("RGB")))
    return actual.read_bytes() == expected.read_bytes()


def check() -> int:
    with tempfile.TemporaryDirectory() as directory:
        temp = Path(directory)
        build(temp)
        failures = []
        manifest = generate_manifest()
        generated_paths = [Path(path) for path in BASE_MANAGED_PATHS]
        for slug in manifest["families"]:
            generated_paths.extend(
                (
                    Path(f"docs/swatches/{slug}.svg"),
                    Path(f"themes/terminal/alacritty/{slug}.toml"),
                    Path(f"themes/terminal/iterm2/{slug}.itermcolors"),
                    Path(f"themes/terminal/windows-terminal/{slug}.json"),
                )
            )
        for relative in generated_paths:
            expected = temp / relative
            actual = ROOT / relative
            if not _artifacts_equal(expected, actual):
                failures.append(str(relative))
        if failures:
            print("stale generated files:")
            print("\n".join(f"  {path}" for path in failures))
            return 1
    print("generated artifacts are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check()
    build(ROOT)
    print("built palette data, terminal themes, and swatches")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
