#!/usr/bin/env python3
"""Build every generated palette artifact from the authoritative definitions."""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import plistlib
import sys
import tempfile
from pathlib import Path

import numpy as np
from PIL import Image

TOOLS = Path(__file__).resolve().parent
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "src"
for local_path in (TOOLS, SRC):
    if str(local_path) not in sys.path:
        sys.path.insert(0, str(local_path))

from render_gallery import GALLERY_FINGERPRINT_KEY, render_matplotlib_gallery
from render_samples import (
    channel_collapse_svg,
    failure_modes_svg,
    redundant_encoding_svg,
    render_samples,
    sample_analysis_markdown,
)
from render_story import render_readme_story
from render_style import publication_chrome

from ember.color import contrast_ratio, hex_to_srgb, wcag_luminance
from ember.generate import ANSI_NAMES, generate_manifest

BASE_MANAGED_PATHS = (
    "palettes/ember.json",
    "palettes/ember.css",
    "src/ember/palettes.json",
    "themes/terminal/README.md",
    "docs/swatches/command-vs-simulated.png",
    "docs/matplotlib-gallery.png",
    "docs/samples/terminal-commanded.png",
    "docs/samples/terminal-simulated.png",
    "docs/samples/terminal-story.png",
    "docs/samples/data-commanded.png",
    "docs/samples/data-simulated.png",
    "docs/samples/data-story.png",
    "docs/diagrams/channel-collapse.svg",
    "docs/diagrams/failure-modes.svg",
    "docs/diagrams/redundant-encoding.svg",
    "docs/sample-analysis.md",
)

ASSET_DIR = ROOT / "assets"
MONA_LISA_SOURCE_IMAGE = ASSET_DIR / "mona-lisa-c2rmf-public-domain.jpg"
MONA_LISA_SOURCE_SHA256 = "5f223c31ba0a477eb7cbe5e5f959d822cbfc46081b19b96498cbd5601d9ac81d"
MONA_LISA_IMAGE_WIDTH = 640
MARS_TOPOGRAPHY_SOURCE = ASSET_DIR / "megt90n000cb.img"
MARS_TOPOGRAPHY_SOURCE_SHA256 = "25f16fb7aaf857898dcf98bc4f841341a24f8b9f7e98453ca083bc45d897ca2c"
MARS_TOPOGRAPHY_LABEL = ASSET_DIR / "megt90n000cb.lbl"
MARS_TOPOGRAPHY_LABEL_SHA256 = "5a3fe60256afa1c35fea5d551fe0ab0a9198fb2bcd2c2e161d078aa69627ebac"
MARS_TOPOGRAPHY_SHAPE = (720, 1440)
MARS_TOPOGRAPHY_DISPLAY_RANGE_METERS = (-5887, 6013)


def _write(path: Path, content: str | bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if isinstance(content, bytes):
        path.write_bytes(content)
    else:
        path.write_text(content, encoding="utf-8")


def _css(manifest: dict) -> str:
    lines = [
        "/* Generated by tools/build_all.py. Do not edit by hand. */",
        "/* Continuous maps expose 11 representative stops; use JSON/Python for all 256. */",
        "",
    ]
    for slug, family in manifest["families"].items():
        lines.append(f'[data-ember-palette="{slug}"] {{')
        for name, value in family["surfaces"].items():
            lines.append(f"  --ember-{name.replace('_', '-')}: {value};")
        for name, value in family["categorical"].items():
            lines.append(f"  --ember-category-{name}: {value};")
        for name in ("red", "green", "yellow", "blue", "magenta", "cyan"):
            lines.append(f"  --ember-terminal-{name}: {family['terminal'][name]};")
        continuous = family["continuous_hex8"]
        stops = [continuous[round(i * 255 / 10)] for i in range(11)]
        gradient = ", ".join(f"{color} {i * 10}%" for i, color in enumerate(stops))
        lines.append(f"  --ember-sequential: linear-gradient(90deg, {gradient});")
        lines.append("}")
        lines.append("")
    return "\n".join(lines)


def _palette_image(indices: np.ndarray, palette: np.ndarray) -> bytes:
    palette_rgb8 = np.rint(palette * 255.0).astype(np.uint8)
    mapped = Image.fromarray(indices.astype(np.uint8))
    mapped.putpalette(palette_rgb8.reshape(-1).tolist())
    output = io.BytesIO()
    mapped.save(output, format="PNG", compress_level=9)
    return output.getvalue()


def _mona_lisa_colormap_image(family: dict) -> bytes:
    """Map source luminance to the family's sequential colors.

    The authored scalar ramp reverses in 3400K Light. Image luminance must not:
    dark source pixels always map to the darker endpoint and light pixels to the
    lighter endpoint, independent of the family's low-to-high scalar direction.
    """

    source_digest = hashlib.sha256(MONA_LISA_SOURCE_IMAGE.read_bytes()).hexdigest()
    if source_digest != MONA_LISA_SOURCE_SHA256:
        raise ValueError("Mona Lisa source image does not match its recorded public-domain asset")

    with Image.open(MONA_LISA_SOURCE_IMAGE) as source:
        source = source.convert("RGB")
        height = round(source.height * MONA_LISA_IMAGE_WIDTH / source.width)
        source = source.resize((MONA_LISA_IMAGE_WIDTH, height), Image.Resampling.LANCZOS)
        source_rgb = np.asarray(source, dtype=float) / 255.0

    luminance = wcag_luminance(source_rgb)
    low, high = np.quantile(luminance, (0.01, 0.99))
    normalized = np.clip((luminance - low) / (high - low), 0.0, 1.0)

    palette = np.asarray(family["continuous_rgb"], dtype=float)
    endpoint_luminance = wcag_luminance(palette[[0, -1]])
    if endpoint_luminance[0] > endpoint_luminance[1]:
        palette = palette[::-1]

    indices = np.rint(normalized * (len(palette) - 1)).astype(np.uint8)
    return _palette_image(indices, palette)


def _mars_topography_colormap_image(family: dict) -> bytes:
    """Map real MOLA elevations through the authored low-to-high scalar ramp."""

    source_digest = hashlib.sha256(MARS_TOPOGRAPHY_SOURCE.read_bytes()).hexdigest()
    label_digest = hashlib.sha256(MARS_TOPOGRAPHY_LABEL.read_bytes()).hexdigest()
    if source_digest != MARS_TOPOGRAPHY_SOURCE_SHA256:
        raise ValueError("MOLA topography source does not match its recorded PDS asset")
    if label_digest != MARS_TOPOGRAPHY_LABEL_SHA256:
        raise ValueError("MOLA topography label does not match its recorded PDS asset")

    elevation = np.fromfile(MARS_TOPOGRAPHY_SOURCE, dtype=">i2")
    expected_size = int(np.prod(MARS_TOPOGRAPHY_SHAPE))
    if elevation.size != expected_size:
        raise ValueError(
            f"MOLA topography source has {elevation.size} samples, expected {expected_size}"
        )
    elevation = elevation.reshape(MARS_TOPOGRAPHY_SHAPE)
    low, high = np.quantile(elevation, (0.01, 0.99))
    display_range = (round(float(low)), round(float(high)))
    if display_range != MARS_TOPOGRAPHY_DISPLAY_RANGE_METERS:
        raise ValueError(f"MOLA display range changed: {display_range}")

    normalized = np.clip((elevation - low) / (high - low), 0.0, 1.0)
    palette = np.asarray(family["continuous_rgb"], dtype=float)
    indices = np.rint(normalized * (len(palette) - 1)).astype(np.uint8)
    return _palette_image(indices, palette)


def _alacritty(family: dict) -> str:
    terminal = family["terminal"]
    normal = {name: terminal[name] for name in ANSI_NAMES[:8]}
    bright = {name.removeprefix("bright_"): terminal[name] for name in ANSI_NAMES[8:]}
    lines = [
        "# Generated by ember/tools/build_all.py",
        f"# Family: {family['name']}",
        "[colors.primary]",
        f'background = "{family["surfaces"]["bg_0"]}"',
        f'foreground = "{family["surfaces"]["fg_0"]}"',
        "",
        "[colors.selection]",
        f'background = "{family["surfaces"]["bg_5"]}"',
        f'text = "{family["surfaces"]["fg_0"]}"',
        "",
        "[colors.normal]",
    ]
    lines.extend(f'{name} = "{value}"' for name, value in normal.items())
    lines.extend(("", "[colors.bright]"))
    lines.extend(f'{name} = "{value}"' for name, value in bright.items())
    return "\n".join(lines) + "\n"


def _windows_terminal(family: dict) -> str:
    terminal = family["terminal"]
    mapping = {
        "black": "black",
        "red": "red",
        "green": "green",
        "yellow": "yellow",
        "blue": "blue",
        "purple": "magenta",
        "cyan": "cyan",
        "white": "white",
        "brightBlack": "bright_black",
        "brightRed": "bright_red",
        "brightGreen": "bright_green",
        "brightYellow": "bright_yellow",
        "brightBlue": "bright_blue",
        "brightPurple": "bright_magenta",
        "brightCyan": "bright_cyan",
        "brightWhite": "bright_white",
    }
    payload = {"name": family["name"]}
    payload.update({key: terminal[value] for key, value in mapping.items()})
    payload["background"] = family["surfaces"]["bg_0"]
    payload["foreground"] = family["surfaces"]["fg_0"]
    payload["selectionBackground"] = family["surfaces"]["bg_5"]
    return json.dumps(payload, indent=2) + "\n"


def _iterm_color(value: str) -> dict:
    rgb = hex_to_srgb(value)
    return {
        "Alpha Component": 1.0,
        "Blue Component": float(rgb[2]),
        "Color Space": "sRGB",
        "Green Component": float(rgb[1]),
        "Red Component": float(rgb[0]),
    }


def _iterm(family: dict) -> bytes:
    terminal = family["terminal"]
    payload = {
        "Background Color": _iterm_color(family["surfaces"]["bg_0"]),
        "Foreground Color": _iterm_color(family["surfaces"]["fg_0"]),
        "Bold Color": _iterm_color(family["surfaces"]["fg_0"]),
        "Selection Color": _iterm_color(family["surfaces"]["bg_5"]),
        "Selected Text Color": _iterm_color(family["surfaces"]["fg_0"]),
    }
    for index, name in enumerate(ANSI_NAMES):
        payload[f"Ansi {index} Color"] = _iterm_color(terminal[name])
    return plistlib.dumps(payload, sort_keys=True)


def _svg_text(
    x: float,
    y: float,
    value: str,
    size: int,
    fill: str,
    *,
    weight: str | None = None,
    anchor: str | None = None,
) -> str:
    escaped = value.replace("&", "&amp;").replace("<", "&lt;")
    attributes = [
        f'x="{x}"',
        f'y="{y}"',
        f'fill="{fill}"',
        f'font-size="{size}"',
        'font-family="ui-monospace, SFMono-Regular, Menlo, monospace"',
    ]
    if weight is not None:
        attributes.append(f'font-weight="{weight}"')
    if anchor is not None:
        attributes.append(f'text-anchor="{anchor}"')
    return f"<text {' '.join(attributes)}>{escaped}</text>"


def _label_color(background: str, chrome: dict[str, str]) -> str:
    background_rgb = hex_to_srgb(background)
    candidates = (chrome["canvas"], chrome["primary"])
    return max(candidates, key=lambda color: contrast_ratio(background_rgb, hex_to_srgb(color)))


def _chip_label_color(family: dict, background: str, chrome: dict[str, str]) -> str:
    if family["slug"] == "3400k-light":
        return chrome["primary"]
    return _label_color(background, chrome)


def _family_svg(family: dict, profile: dict, chrome: dict[str, str]) -> str:
    width, height = 760, 632
    margin, content_width = 32, 696
    background_roles = tuple(f"bg_{index}" for index in range(6))
    foreground_roles = tuple(f"fg_{index}" for index in range(3))
    terminal_roles = (
        ("red", "R"),
        ("green", "G"),
        ("yellow", "Y"),
        ("blue", "B"),
        ("magenta", "M"),
        ("cyan", "C"),
    )

    first_letter_by_index: dict[int, str] = {}
    terminal_labels = []
    alias_labels = []
    for (_, letter), index in zip(terminal_roles, family["terminal_ansi_indices"]):
        first = first_letter_by_index.setdefault(index, letter)
        label = letter if first == letter else f"{letter}={first}"
        terminal_labels.append(label)
        if "=" in label:
            alias_labels.append(label)

    capacity = (
        f"{len(family['categorical'])} categories · "
        f"{family['terminal_semantic_color_count']} terminal accents"
    )
    if alias_labels:
        capacity = (
            f"{len(family['categorical'])} categories · "
            f"{family['terminal_semantic_color_count']} accents · {' '.join(alias_labels)}"
        )

    canvas = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        f'<rect width="100%" height="100%" rx="20" fill="{chrome["canvas"]}"/>',
        _svg_text(32, 54, family["name"], 34, chrome["primary"], weight="700"),
        _svg_text(728, 50, capacity, 20, chrome["secondary"], anchor="end"),
        _svg_text(32, 80, f"{profile['target']} · commanded sRGB", 14, chrome["metadata"]),
        f'<line x1="32" y1="98" x2="728" y2="98" stroke="{chrome["rule"]}"/>',
    ]

    canvas.append(_svg_text(32, 130, "SURFACES · bg_0 → bg_5", 15, chrome["secondary"]))
    chip_gap = 10
    six_chip_width = (content_width - chip_gap * 5) / 6
    for index, role in enumerate(background_roles):
        value = family["surfaces"][role]
        x, y = margin + index * (six_chip_width + chip_gap), 142
        canvas.append(
            f'<rect x="{x:.2f}" y="{y}" width="{six_chip_width:.2f}" height="64" '
            f'rx="8" fill="{value}" stroke="{chrome["border"]}"/>'
        )
        label_fill = _label_color(value, chrome)
        canvas.append(_svg_text(x + 10, y + 24, role, 16, label_fill))
        canvas.append(_svg_text(x + 10, y + 50, value, 16, label_fill))

    canvas.append(_svg_text(32, 240, "TEXT ON bg_0 · fg_0 fg_1 fg_2", 15, chrome["secondary"]))
    bg_0 = family["surfaces"]["bg_0"]
    canvas.append(
        f'<rect x="32" y="252" width="696" height="58" rx="8" fill="{bg_0}" '
        f'stroke="{chrome["border"]}"/>'
    )
    for x, role in zip((52, 284, 516), foreground_roles):
        value = family["surfaces"][role]
        canvas.append(_svg_text(x, 288, f"{role} · {value}", 16, value))

    count = len(family["categorical"])
    canvas.append(_svg_text(32, 348, f"CATEGORICAL · {count} COLORS", 15, chrome["secondary"]))
    category_width = (content_width - chip_gap * (count - 1)) / count
    for index, value in enumerate(family["categorical"].values()):
        x, y = margin + index * (category_width + chip_gap), 360
        label_fill = _chip_label_color(family, value, chrome)
        canvas.append(
            f'<rect x="{x:.2f}" y="{y}" width="{category_width:.2f}" height="58" '
            f'rx="8" fill="{value}" stroke="{chrome["border"]}"/>'
        )
        canvas.append(
            _svg_text(
                x + category_width / 2,
                y + 35,
                value,
                16,
                label_fill,
                anchor="middle",
            )
        )

    identity_count = family["terminal_semantic_color_count"]
    canvas.append(
        _svg_text(
            32,
            456,
            f"TERMINAL ANSI · {identity_count} IDENTITIES / 16 SLOTS",
            15,
            chrome["secondary"],
        )
    )
    for index, ((role, _letter), label) in enumerate(zip(terminal_roles, terminal_labels)):
        value = family["terminal"][role]
        x, y = margin + index * (six_chip_width + chip_gap), 468
        dash = ' stroke-dasharray="5 4"' if "=" in label else ""
        label_fill = _chip_label_color(family, value, chrome)
        canvas.append(
            f'<rect x="{x:.2f}" y="{y}" width="{six_chip_width:.2f}" height="58" '
            f'rx="8" fill="{value}" stroke="{chrome["border"]}"{dash}/>'
        )
        canvas.append(
            _svg_text(
                x + six_chip_width / 2,
                y + 37,
                label,
                18 if "=" in label else 22,
                label_fill,
                weight="700",
                anchor="middle",
            )
        )

    continuous = family["continuous_hex8"]
    canvas.append(
        _svg_text(
            32,
            564,
            "SEQUENTIAL · 256 SAMPLES · LOW → HIGH",
            15,
            chrome["secondary"],
        )
    )
    for index, value in enumerate(continuous):
        x = margin + index * content_width / len(continuous)
        slice_width = min(2.9, 728 - x)
        canvas.append(
            f'<rect x="{x:.4f}" y="576" width="{slice_width:.4f}" height="32" fill="{value}"/>'
        )
    canvas.append("</svg>")
    return "\n".join(canvas)


def build(destination: Path) -> None:
    manifest = generate_manifest()
    chrome = publication_chrome(manifest)
    encoded = json.dumps(manifest, indent=2) + "\n"
    _write(destination / "palettes/ember.json", encoded)
    _write(destination / "src/ember/palettes.json", encoded)
    _write(destination / "palettes/ember.css", _css(manifest))
    terminal_readme = """# Terminal themes

Generated imports are provided for Alacritty, iTerm2, and Windows Terminal. Each
uses the family’s primary background and foreground. Alternative surfaces live in
the JSON manifest, generated CSS, and Python `surfaces()` API; substitute them when a
different canvas is needed. Terminal formats themselves expose only their native primary
background and selection roles; generated themes map those to `bg_0` and `bg_5`.

## Install

### Alacritty

Copy one TOML file into your Alacritty configuration directory, then import it
from `alacritty.toml`:

```toml
[general]
import = ["~/.config/alacritty/themes/2000k-dark.toml"]
```

Restart Alacritty or reload its configuration.

### iTerm2

Open **Settings → Profiles → Colors → Color Presets… → Import…**, choose a
`.itermcolors` file, then select the imported preset from **Color Presets…**.

### Windows Terminal

Open **Settings → Open JSON file**. Copy one generated scheme object into the
root `schemes` array, then set a profile’s `colorScheme` to the object’s exact
`name` value, such as `2000K Dark`.

## Surface roles

Terminal formats require all 16 ANSI slots. Ember repeats 6, 6, 4, or 3
commanded daytime accents across those slots. Under the target transforms they form
6, 6, 4, or 3 distinct nighttime identities. Bold should come from typography,
not a second high-chroma bank.

Reduced banks preserve recognizable ANSI roles by day. At 1200 K, magenta aliases red,
cyan aliases green, and blue aliases yellow instead of using a modulo cycle that would
assign those names to misleading hues.

`fg_0` is the body-text role. `fg_1` is intended for larger supporting text or graphics,
and `fg_2` for nonessential metadata or decoration. The latter two are not universal
body-text colors; inspect each
pairing under `metrics.shifted_text_contrast` in the JSON manifest.
"""
    _write(destination / "themes/terminal/README.md", terminal_readme)

    for slug, family in manifest["families"].items():
        _write(destination / f"themes/terminal/alacritty/{slug}.toml", _alacritty(family))
        _write(
            destination / f"themes/terminal/windows-terminal/{slug}.json", _windows_terminal(family)
        )
        _write(destination / f"themes/terminal/iterm2/{slug}.itermcolors", _iterm(family))
        profile = manifest["profiles"][family["profile"]]
        _write(destination / f"docs/swatches/{slug}.svg", _family_svg(family, profile, chrome))
        _write(destination / f"assets/mona-lisa-{slug}.png", _mona_lisa_colormap_image(family))
        _write(
            destination / f"assets/mars-topography-{slug}.png",
            _mars_topography_colormap_image(family),
        )

    render_readme_story(manifest, destination / "docs")
    render_matplotlib_gallery(manifest, destination / "docs/matplotlib-gallery.png")
    render_samples(manifest, destination / "docs/samples")
    _write(destination / "docs/diagrams/channel-collapse.svg", channel_collapse_svg(manifest))
    _write(destination / "docs/diagrams/failure-modes.svg", failure_modes_svg(manifest))
    _write(
        destination / "docs/diagrams/redundant-encoding.svg",
        redundant_encoding_svg(manifest),
    )
    _write(
        destination / "docs/sample-analysis.md",
        sample_analysis_markdown(manifest, destination / "docs/samples"),
    )


def _artifacts_equal(expected: Path, actual: Path) -> bool:
    if not actual.exists():
        return False
    if expected.suffix == ".png":
        with Image.open(expected) as left, Image.open(actual) as right:
            if expected.name == "matplotlib-gallery.png":
                # Matplotlib text rasterization varies across supported Python/platform
                # wheels. Compare the source fingerprint and canvas, not incidental pixels.
                return left.size == right.size and left.info.get(
                    GALLERY_FINGERPRINT_KEY
                ) == right.info.get(GALLERY_FINGERPRINT_KEY)
            return np.array_equal(np.asarray(left.convert("RGB")), np.asarray(right.convert("RGB")))
    return actual.read_bytes() == expected.read_bytes()


def check() -> int:
    with tempfile.TemporaryDirectory() as directory:
        temp = Path(directory)
        build(temp)
        failures = []
        manifest = generate_manifest()
        generated_paths = [Path(path) for path in BASE_MANAGED_PATHS]
        for slug in manifest["families"]:
            generated_paths.extend(
                (
                    Path(f"docs/swatches/{slug}.svg"),
                    Path(f"themes/terminal/alacritty/{slug}.toml"),
                    Path(f"themes/terminal/iterm2/{slug}.itermcolors"),
                    Path(f"themes/terminal/windows-terminal/{slug}.json"),
                    Path(f"assets/mona-lisa-{slug}.png"),
                    Path(f"assets/mars-topography-{slug}.png"),
                )
            )

        for relative in generated_paths:
            expected = temp / relative
            actual = ROOT / relative
            if not _artifacts_equal(expected, actual):
                failures.append(str(relative))
        if failures:
            print("stale generated files:")
            print("\n".join(f"  {path}" for path in failures))
            return 1
    print("generated artifacts are current")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    if args.check:
        return check()
    build(ROOT)
    print("built palette data, terminal themes, and swatches")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
